### PR TITLE
fix std::result_of usage

### PR DESCRIPTION
**Pull request by loganek**

### CODE REVIEW

**Comment by murraycu** [comment]
Wonderful. Thanks.

**Comment by murraycu** [comment]
I'm now moved this into master, now that it works.

**Comment by murraycu** [comment]
By the way, the need for a static transform() function isn't pretty. If we were passing an actual instance of a functor, we'd want to use operator() instead, but I can't think of anything similar for just a (templated) type.

**Comment by loganek** [comment]
Yeah, I noted it. I'll try to improve this part of code when I have some time. Let me know, if you have any thoughts about it.

**Comment by murraycu** [comment]
Thanks.

Maybe you can also see how we might get this working:
https://github.com/murraycu/murrayc-tuple-utils/commits/for_each_nonconst

It should let the visit() function change the tuple element. It compiles but, as the test shows, it doesn't seem to actually do what it should.

I only really need this for tuple_transform_each(), because libsigc++'s bound_argument::invoke() is not const, but I thought I'd try it on the simpler tuple_for_each() first.

**Comment by murraycu** [comment]
I tried many ways to fix that, but for now I've given up and just split it into tuple_for_each() and tuple_for_each_const(). It would be great if someone figures out how to avoid that awful ugliness.

**Pull request merged**
